config/routes.rb
SurveyRails::Application.routes.draw do
  
  resources :users
  resources :session
  resources :surveys do
    collection do
      post 'take'
      get 'results'
    end
  end

  resources :questions do
    collection do
      post 'answer'
    end
  end
  

  root :to => 'surveys#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
  belongs_to :possible_answer

  attr_accessible :answer_text, :possible_answer, :question, :user
end

app/models/possible_answer.rb
class PossibleAnswer < ActiveRecord::Base
  belongs_to :question
  has_many :users, through: :question

  attr_accessible :answer_text
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :survey
  has_many :answers
  has_many :possible_answers

  attr_accessible :question_text
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  belongs_to :creator, class_name: "User"
  has_many :questions
  has_many :user_surveys
  has_many :users, through: :user_surveys

  attr_accessible :title, :questions, :creator
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :user_surveys
  has_many :surveys, through: :user_surveys
  has_many :created_surveys, class_name: "Survey", foreign_key: :creator_id
  has_many :answers

  validates_uniqueness_of :email
  validates_presence_of :name, :email, :password, :password_confirmation

  has_secure_password

  attr_accessible :name, :email, :password, :password_confirmation
end

app/models/user_survey.rb
class UserSurvey < ActiveRecord::Base
  belongs_to :user
  belongs_to :survey
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def create
    user = User.find_by_email(params[:user][:email])
    if user && user.authenticate(params[:user][:password])
      session[:user_id] = user
      redirect_to user_url(session[:user_id])
    else
      render :new
    end
  end

  def new
    @user = User.new
  end

  def destroy
    session.clear
    redirect_to root_url
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  include SurveyHelper

  def index
    @surveys = Survey.all
  end
  
  def take
    @survey = Survey.find(params[:id])
  end

  def show
    @survey = current_survey
  end

  def results
    @survey = current_survey
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    user = User.create(params[:user])
    
    unless user.id.nil?
      session[user.id]
      redirect_to user_url(user)
    else
      redirect_to new_user_url
    end
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
    @current_user =  User.find(session[:user_id]) if session[:user_id]
  end

  def update
    user = User.find(params[:id])
    if user.update_attributes(name: params[:user][:name])
      redirect_to user_url(user)
    else
      redirect_to edit_user_url(user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/survey_helper.rb
module SurveyHelper
  def current_survey
    @survey ||= Survey.find_by_id(params[:id])
  end

end

app/helpers/user_helper.rb
module UserHelper
  def self.current_user
    @user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SurveyRails</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/session/new.haml
%p Sign In!

= form_for @user, url: session_index_url do |f|
  .field= f.label :email
  .field= f.text_field :email
  .field= f.label :password
  .field= f.password_field :password
  .field= f.submit

app/views/surveys/index.haml
%h2 Here's our surveys, y'all!

= content_tag_for(:li, @surveys) do |survey|
  %b= survey.title
  =link_to "Take Survey", survey_url(survey)

app/views/surveys/show.haml
%h2= @survey.title

= @survey.questions.each do |question|
  %h4= question.question_text
  = form_for question, url: answer_questions_url do |f|
    = f.label :text
    = f.text_field :text

app/views/users/_form.haml
= form_for @user do |f| 
 .field= f.label :name
 .field= f.text_field :name
 .field= f.label :email
 .field= f.text_field :email
 .field= f.label :password
 .field= f.password_field :password
 .field= f.label :password_confirmation
 .field= f.password_field :password_confirmation
 .field= f.submit

app/views/users/edit.haml
%h2 Edit, Bitches!

= render :partial => "form"

app/views/users/new.haml
%h2 Sign up, Bitches!

= render partial: "form"

app/views/users/show.haml
%p= @user.name
%p= @user.email

= if session[:user_id]
  = link_to "Log Out", session_url, method: :delete